---
- name: Add an apt signing key for Kubernetes
  become: yes
  ansible.builtin.apt_key:
    url: "{{ kubernetes_gpg_key_url }}"
    state: present

- name: Adding apt repository for Kubernetes
  become: yes
  ansible.builtin.apt_repository:
    repo: "{{ kubernetes_repository }}"
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  become: yes
  ansible.builtin.apt: 
    name: "{{ kubernetes_packages }}"
    state: present
    update_cache: yes
  notify: start kubelet

- meta: flush_handlers