---
docker_repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
distro_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common
docker_packages:
- containerd.io